### ISSUE TITLE
[Borealis] Allow sorting time series input

### ISSUE THREAD

**Issue by WouterWouters** [timeseer-ai/kukur#100]
Data in Delta lake is unordered.

Sort in source (Kukur).

```toml
[source.<>]
sort_by_timestamp = true
```
