### ISSUE TITLE
Fail when tag columns are not present in the data

### ISSUE THREAD

**Issue by jhoekx** [timeseer-ai/kukur#220]
This configuration is invalid:

```toml
[source.name]
type = "feather"
path = "data/name.feather"
format = "row"
tag_columns = ["serialNo", "type", "location"]

[source.name.column_mapping]
"series name" = "serialNo"
```

We should produce an error.

After mapping the `serialNo` column to `series name`, the configured tag column `serialNo` no longer exists. It should be `series name`.
