### ISSUE TITLE
Support assembling timestamps from multiple columns

### ISSUE THREAD

**Issue by jhoekx** [timeseer-ai/kukur#97]
In the Feather, Parquet, CSV and Delta sources, support assembling the `ts` column from multiple other columns.

```toml
[source.<>]
...
data_timezone = "UTC"

[source.<>.ts]
year = "year"
month = "month"
day = "day"
time = "ts"
```

Supported partial columns are:
- `year`
- `month`
- `day`
- `hour`
- `minute`
- `second`
- `date`
- `time`
- `datetime`
- `timezone`

If the timezone is not part of the data, use `data_timezone` in the source configuration.
